// Code generated by goyacc -o generated_parser.y.go generated_parser.y. DO NOT EDIT.

//line generated_parser.y:15
package parser

import __yyfmt__ "fmt"

//line generated_parser.y:15

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"time"

	"github.com/prometheus/prometheus/pkg/labels"
	"github.com/prometheus/prometheus/pkg/value"
)

//line generated_parser.y:29
type yySymType struct {
	yys      int
	node     Node
	llist    *CommentLinkedList
	item     Item
	matchers []*labels.Matcher
	matcher  *labels.Matcher
	label    labels.Label
	labels   labels.Labels
	strings  []string
	series   []SequenceValue
	uint     uint64
	float    float64
	duration time.Duration
}

const ASSIGN = 57346
const BLANK = 57347
const COLON = 57348
const COMMA = 57349
const COMMENT = 57350
const DURATION = 57351
const EOF = 57352
const ERROR = 57353
const IDENTIFIER = 57354
const LEFT_BRACE = 57355
const LEFT_BRACKET = 57356
const LEFT_PAREN = 57357
const METRIC_IDENTIFIER = 57358
const NUMBER = 57359
const RIGHT_BRACE = 57360
const RIGHT_BRACKET = 57361
const RIGHT_PAREN = 57362
const SEMICOLON = 57363
const SPACE = 57364
const STRING = 57365
const TIMES = 57366
const operatorsStart = 57367
const ADD = 57368
const DIV = 57369
const EQL = 57370
const EQL_REGEX = 57371
const GTE = 57372
const GTR = 57373
const LAND = 57374
const LOR = 57375
const LSS = 57376
const LTE = 57377
const LUNLESS = 57378
const MOD = 57379
const MUL = 57380
const NEQ = 57381
const NEQ_REGEX = 57382
const POW = 57383
const SUB = 57384
const operatorsEnd = 57385
const aggregatorsStart = 57386
const AVG = 57387
const BOTTOMK = 57388
const COUNT = 57389
const COUNT_VALUES = 57390
const MAX = 57391
const MIN = 57392
const QUANTILE = 57393
const STDDEV = 57394
const STDVAR = 57395
const SUM = 57396
const TOPK = 57397
const aggregatorsEnd = 57398
const keywordsStart = 57399
const BOOL = 57400
const BY = 57401
const GROUP_LEFT = 57402
const GROUP_RIGHT = 57403
const IGNORING = 57404
const OFFSET = 57405
const ON = 57406
const WITHOUT = 57407
const keywordsEnd = 57408
const startSymbolsStart = 57409
const START_METRIC = 57410
const START_SERIES_DESCRIPTION = 57411
const START_EXPRESSION = 57412
const START_METRIC_SELECTOR = 57413
const startSymbolsEnd = 57414

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ASSIGN",
	"BLANK",
	"COLON",
	"COMMA",
	"COMMENT",
	"DURATION",
	"EOF",
	"ERROR",
	"IDENTIFIER",
	"LEFT_BRACE",
	"LEFT_BRACKET",
	"LEFT_PAREN",
	"METRIC_IDENTIFIER",
	"NUMBER",
	"RIGHT_BRACE",
	"RIGHT_BRACKET",
	"RIGHT_PAREN",
	"SEMICOLON",
	"SPACE",
	"STRING",
	"TIMES",
	"operatorsStart",
	"ADD",
	"DIV",
	"EQL",
	"EQL_REGEX",
	"GTE",
	"GTR",
	"LAND",
	"LOR",
	"LSS",
	"LTE",
	"LUNLESS",
	"MOD",
	"MUL",
	"NEQ",
	"NEQ_REGEX",
	"POW",
	"SUB",
	"operatorsEnd",
	"aggregatorsStart",
	"AVG",
	"BOTTOMK",
	"COUNT",
	"COUNT_VALUES",
	"MAX",
	"MIN",
	"QUANTILE",
	"STDDEV",
	"STDVAR",
	"SUM",
	"TOPK",
	"aggregatorsEnd",
	"keywordsStart",
	"BOOL",
	"BY",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"IGNORING",
	"OFFSET",
	"ON",
	"WITHOUT",
	"keywordsEnd",
	"startSymbolsStart",
	"START_METRIC",
	"START_SERIES_DESCRIPTION",
	"START_EXPRESSION",
	"START_METRIC_SELECTOR",
	"startSymbolsEnd",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line generated_parser.y:829

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 31,
	1, 135,
	10, 135,
	22, 135,
	-2, 0,
	-1, 55,
	2, 148,
	15, 148,
	59, 148,
	65, 148,
	-2, 105,
	-1, 56,
	2, 149,
	15, 149,
	59, 149,
	65, 149,
	-2, 106,
	-1, 57,
	2, 150,
	15, 150,
	59, 150,
	65, 150,
	-2, 108,
	-1, 58,
	2, 151,
	15, 151,
	59, 151,
	65, 151,
	-2, 109,
	-1, 59,
	2, 152,
	15, 152,
	59, 152,
	65, 152,
	-2, 114,
	-1, 60,
	2, 153,
	15, 153,
	59, 153,
	65, 153,
	-2, 116,
	-1, 61,
	2, 154,
	15, 154,
	59, 154,
	65, 154,
	-2, 118,
	-1, 62,
	2, 155,
	15, 155,
	59, 155,
	65, 155,
	-2, 119,
	-1, 63,
	2, 156,
	15, 156,
	59, 156,
	65, 156,
	-2, 120,
	-1, 64,
	2, 157,
	15, 157,
	59, 157,
	65, 157,
	-2, 121,
	-1, 65,
	2, 158,
	15, 158,
	59, 158,
	65, 158,
	-2, 122,
	-1, 191,
	12, 197,
	13, 197,
	16, 197,
	17, 197,
	23, 197,
	26, 197,
	32, 197,
	33, 197,
	36, 197,
	42, 197,
	45, 197,
	46, 197,
	47, 197,
	48, 197,
	49, 197,
	50, 197,
	51, 197,
	52, 197,
	53, 197,
	54, 197,
	55, 197,
	59, 197,
	63, 197,
	-2, 0,
	-1, 192,
	12, 197,
	13, 197,
	16, 197,
	17, 197,
	23, 197,
	26, 197,
	32, 197,
	33, 197,
	36, 197,
	42, 197,
	45, 197,
	46, 197,
	47, 197,
	48, 197,
	49, 197,
	50, 197,
	51, 197,
	52, 197,
	53, 197,
	54, 197,
	55, 197,
	59, 197,
	63, 197,
	-2, 0,
	-1, 208,
	19, 195,
	-2, 0,
	-1, 255,
	19, 196,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 579

var yyAct = [...]int{

	261, 35, 212, 150, 252, 251, 184, 122, 73, 183,
	111, 110, 113, 189, 135, 190, 129, 214, 114, 131,
	191, 192, 245, 112, 186, 264, 244, 223, 54, 243,
	130, 229, 177, 239, 78, 267, 115, 265, 259, 124,
	187, 262, 128, 258, 159, 185, 238, 225, 226, 123,
	242, 227, 117, 176, 118, 240, 257, 158, 6, 116,
	215, 217, 219, 220, 228, 230, 233, 234, 235, 236,
	237, 97, 68, 216, 218, 221, 222, 224, 231, 232,
	113, 115, 119, 81, 82, 83, 114, 84, 85, 86,
	87, 88, 89, 90, 91, 92, 93, 29, 94, 95,
	80, 153, 136, 137, 138, 139, 140, 141, 142, 143,
	144, 145, 146, 147, 148, 149, 7, 163, 157, 160,
	96, 155, 256, 156, 2, 3, 4, 5, 97, 152,
	154, 79, 99, 188, 266, 175, 77, 152, 193, 194,
	195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
	205, 206, 209, 151, 179, 94, 208, 181, 214, 30,
	152, 182, 167, 75, 1, 127, 185, 166, 223, 207,
	126, 254, 229, 74, 241, 186, 211, 96, 165, 174,
	10, 125, 53, 124, 45, 9, 9, 246, 225, 226,
	70, 187, 227, 123, 249, 250, 247, 248, 253, 121,
	97, 215, 217, 219, 220, 228, 230, 233, 234, 235,
	236, 237, 255, 82, 216, 218, 221, 222, 224, 231,
	232, 8, 46, 91, 92, 31, 44, 94, 69, 34,
	43, 33, 75, 48, 68, 42, 50, 21, 49, 134,
	41, 260, 74, 40, 51, 39, 263, 66, 72, 96,
	132, 161, 38, 17, 18, 133, 37, 19, 36, 180,
	76, 268, 178, 67, 210, 269, 55, 56, 57, 58,
	59, 60, 61, 62, 63, 64, 65, 71, 48, 68,
	13, 50, 21, 49, 23, 52, 162, 213, 168, 51,
	47, 120, 66, 0, 0, 0, 0, 0, 17, 18,
	0, 0, 19, 0, 0, 0, 0, 0, 67, 0,
	0, 55, 56, 57, 58, 59, 60, 61, 62, 63,
	64, 65, 97, 79, 0, 13, 0, 48, 68, 23,
	50, 21, 49, 0, 81, 82, 0, 0, 51, 0,
	0, 66, 0, 0, 0, 91, 92, 17, 18, 94,
	95, 19, 0, 169, 0, 0, 0, 67, 0, 0,
	55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
	65, 96, 48, 68, 13, 50, 21, 49, 23, 170,
	172, 0, 0, 51, 0, 0, 66, 0, 0, 0,
	171, 173, 17, 18, 0, 0, 19, 16, 68, 0,
	0, 21, 67, 0, 0, 55, 56, 57, 58, 59,
	60, 61, 62, 63, 64, 65, 0, 17, 18, 13,
	0, 19, 0, 23, 0, 16, 29, 0, 0, 21,
	11, 12, 14, 15, 20, 22, 24, 25, 26, 27,
	28, 0, 0, 0, 13, 17, 18, 0, 23, 19,
	0, 0, 0, 0, 0, 0, 0, 0, 11, 12,
	14, 15, 20, 22, 24, 25, 26, 27, 28, 97,
	0, 0, 13, 0, 0, 164, 23, 0, 0, 0,
	0, 81, 82, 83, 0, 84, 85, 86, 87, 88,
	89, 90, 91, 92, 93, 0, 94, 95, 0, 97,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 81, 82, 83, 0, 84, 85, 86, 96, 88,
	89, 90, 91, 92, 93, 32, 94, 95, 0, 97,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 81, 82, 83, 0, 84, 85, 0, 96, 88,
	89, 0, 91, 92, 93, 0, 94, 95, 0, 0,
	0, 0, 98, 100, 101, 102, 103, 104, 105, 106,
	107, 108, 109, 0, 0, 0, 0, 0, 96,
}
var yyPact = [...]int{

	56, 106, 413, 413, 221, 385, -1000, -1000, -1000, 84,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 230,
	-1000, 134, 315, -1000, 90, 57, 124, 124, 124, 124,
	124, 124, 124, 124, 124, 124, 124, 21, 66, -1000,
	360, -1000, 360, 59, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 181, -1000,
	-1000, 163, -1000, -1000, 14, -1000, 8, -1000, 57, -1000,
	-1000, -44, -44, -44, -44, -44, -44, -44, -44, -44,
	-44, -44, -44, -44, -44, -44, 151, 128, 123, -1000,
	123, 123, 123, 123, 123, 123, 123, 123, 123, 123,
	66, -47, -1000, 42, 42, 266, -1000, 455, 114, -1000,
	160, -1000, -1000, 351, -1000, -1000, 161, -1000, 30, -1000,
	149, 360, -1000, -49, -40, -1000, 360, 360, 360, 360,
	360, 360, 360, 360, 360, 360, 360, 360, 360, 360,
	-1000, -1000, -1000, 150, -1000, -1000, -1000, -1000, 156, -1000,
	-1000, 26, -1000, 57, -1000, -1000, 37, -1000, 27, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 2,
	-2, -1000, -1000, -1000, -1000, -1000, 28, 28, 186, 42,
	42, 42, 42, 114, 308, 308, 308, 515, 485, 308,
	308, 515, 114, 114, 308, 114, 186, -1000, 120, -1000,
	36, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 360,
	-1000, -1000, -1000, -1000, 24, 24, 1, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 18, 132, -1000, -1000, 15, -1000,
	57, -1000, -1000, -1000, 24, -1000, -1000, -1000, -1000, -1000,
}
var yyPgo = [...]int{

	0, 291, 7, 290, 2, 288, 287, 182, 285, 180,
	277, 221, 8, 264, 4, 5, 262, 260, 0, 9,
	259, 6, 258, 11, 19, 256, 255, 1, 252, 251,
	10, 250, 28, 245, 243, 240, 239, 235, 230, 226,
	184, 222, 3, 171, 525, 164, 159,
}
var yyR1 = [...]int{

	0, 45, 45, 45, 45, 45, 45, 45, 45, 45,
	45, 27, 27, 27, 27, 27, 27, 27, 27, 27,
	27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
	27, 27, 27, 44, 44, 22, 22, 22, 22, 23,
	23, 25, 25, 25, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 25, 25, 25, 24, 26, 26, 36,
	36, 31, 31, 31, 31, 14, 14, 14, 14, 13,
	13, 13, 4, 4, 28, 30, 30, 29, 29, 29,
	37, 35, 35, 33, 39, 39, 39, 39, 39, 40,
	41, 41, 41, 32, 32, 32, 1, 1, 1, 2,
	2, 2, 2, 11, 11, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 9, 9, 9, 9, 10, 10, 10,
	12, 12, 12, 12, 46, 17, 17, 17, 17, 16,
	16, 16, 16, 16, 20, 20, 20, 20, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 8, 8, 5, 5, 5, 5, 34, 19,
	21, 21, 18, 42, 38, 43, 43, 15, 15,
}
var yyR2 = [...]int{

	0, 2, 2, 2, 3, 2, 3, 2, 2, 2,
	1, 1, 2, 1, 2, 1, 2, 1, 2, 1,
	2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
	2, 1, 2, 1, 2, 3, 3, 2, 2, 2,
	2, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 1, 0, 1, 3,
	3, 1, 1, 3, 3, 3, 4, 2, 1, 3,
	1, 2, 1, 1, 2, 3, 2, 3, 1, 2,
	3, 3, 3, 4, 6, 6, 5, 4, 3, 2,
	2, 1, 1, 3, 4, 2, 3, 1, 2, 3,
	3, 2, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 4, 2, 0, 3, 1, 2,
	3, 3, 2, 1, 2, 0, 3, 2, 1, 1,
	3, 1, 3, 4, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	2, 2, 1, 1, 1, 0, 1, 0, 1,
}
var yyChk = [...]int{

	-1000, -45, 68, 69, 70, 71, 2, 10, -11, -7,
	-9, 45, 46, 59, 47, 48, 12, 32, 33, 36,
	49, 16, 50, 63, 51, 52, 53, 54, 55, 13,
	-46, -11, -44, 10, 8, -27, -22, -25, -28, -33,
	-34, -35, -37, -38, -39, -40, -41, -3, 12, 17,
	15, 23, -8, -7, -32, 45, 46, 47, 48, 49,
	50, 51, 52, 53, 54, 55, 26, 42, 13, -41,
	-9, -10, 18, -12, 12, 2, -17, 2, -27, 8,
	10, 26, 27, 28, 30, 31, 32, 33, 34, 35,
	36, 37, 38, 39, 41, 42, 63, 14, -44, 8,
	-44, -44, -44, -44, -44, -44, -44, -44, -44, -44,
	-23, -30, 2, 59, 65, 15, -30, -27, -27, -32,
	-1, 18, -2, 12, 2, 18, 7, 2, 28, 2,
	22, -24, -31, -26, -36, 58, -24, -24, -24, -24,
	-24, -24, -24, -24, -24, -24, -24, -24, -24, -24,
	-42, 2, 9, -42, 2, -30, -23, -14, 15, 2,
	-14, -29, 20, -27, 20, 18, 7, 2, -5, 2,
	28, 39, 29, 40, 18, -12, 23, 2, -16, 5,
	-20, 8, 12, -19, -21, 17, 26, 42, -27, 62,
	64, 60, 61, -27, -27, -27, -27, -27, -27, -27,
	-27, -27, -27, -27, -27, -27, -27, 19, 6, 2,
	-13, 20, -4, -6, 2, 45, 58, 46, 59, 47,
	48, 60, 61, 12, 62, 32, 33, 36, 49, 16,
	50, 63, 64, 51, 52, 53, 54, 55, 20, 7,
	18, -2, 23, 2, 24, 24, -21, -19, -19, -14,
	-14, -15, -14, -15, -43, -42, 2, 20, 7, 2,
	-27, -18, 17, -18, 24, 19, 2, 20, -4, -18,
}
var yyDef = [...]int{

	0, -2, 126, 126, 0, 0, 10, 9, 1, 126,
	104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
	114, 115, 116, 117, 118, 119, 120, 121, 122, 0,
	2, -2, 3, 5, 33, 7, 11, 13, 15, 17,
	19, 21, 23, 25, 27, 29, 31, 0, 110, 188,
	0, 194, 0, 91, 92, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, 182, 183, 0, 8,
	103, 0, 125, 128, 0, 133, 134, 138, 4, 34,
	6, 57, 57, 57, 57, 57, 57, 57, 57, 57,
	57, 57, 57, 57, 57, 57, 0, 0, 12, 33,
	14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
	0, 37, 38, 0, 0, 0, 74, 0, 89, 90,
	0, 95, 97, 0, 102, 123, 0, 129, 0, 132,
	137, 0, 56, 61, 62, 58, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	81, 82, 193, 0, 88, 35, 36, 39, 0, 68,
	40, 0, 76, 78, 80, 93, 0, 98, 0, 101,
	184, 185, 186, 187, 124, 127, 130, 131, 136, 139,
	141, 144, 145, 146, 147, 189, 0, 0, 41, 0,
	0, -2, -2, 42, 43, 44, 45, 46, 47, 48,
	49, 50, 51, 52, 53, 54, 55, 83, -2, 87,
	0, 67, 70, 72, 73, 159, 160, 161, 162, 163,
	164, 165, 166, 167, 168, 169, 170, 171, 172, 173,
	174, 175, 176, 177, 178, 179, 180, 181, 75, 79,
	94, 96, 99, 100, 0, 0, 0, 190, 191, 59,
	60, 63, 198, 64, 0, -2, 86, 65, 0, 71,
	77, 140, 192, 142, 0, 84, 85, 66, 69, 143,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:167
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].labels
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:170
		{
			ce := &CommentExpr{
				IsHead:     true,
				CommentPtr: yyDollar[2].llist,
			}
			yylex.(*parser).generatedParserResult = ce
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:178
		{
			ce := &CommentExpr{
				IsHead:     true,
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[3].node.(Expr),
				PosRange:   yyDollar[3].node.PositionRange(),
			}
			yylex.(*parser).generatedParserResult = ce
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:188
		{
			yylex.(*parser).addParseErrf(PositionRange{}, "no expression found in input")
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:190
		{
			yylex.(*parser).addParseErrf(PositionRange{}, "no expression found in input")
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:192
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:194
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:197
		{
			yylex.(*parser).unexpected("", "")
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:203
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}

		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:212
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:220
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:228
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:236
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:244
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:252
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:260
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:268
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:276
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:284
		{
			yyVAL.node = &CommentExpr{
				CommentPtr: yyDollar[2].llist,
				Expr:       yyDollar[1].node.(Expr),
			}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:294
		{
			yyVAL.llist = &CommentLinkedList{
				Comment: yyDollar[1].item.Val,
				Addr:    nil,
			}
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:301
		{
			yyVAL.llist = &CommentLinkedList{
				Comment: yyDollar[2].item.Val,
				Addr:    yyDollar[1].llist,
			}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:314
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[2].node, yyDollar[3].node)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:316
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[3].node, yyDollar[2].node)
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:318
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, yyDollar[2].node)
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:320
		{
			yylex.(*parser).unexpected("aggregation", "")
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, Expressions{})
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:328
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
			}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:334
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
				Without:  true,
			}
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:347
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:348
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:349
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:350
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:351
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:352
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:353
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 48:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:354
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 49:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:355
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:356
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:357
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:358
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:359
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:360
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:361
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 57:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:369
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
			}
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:374
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
				ReturnBool:     true,
			}
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:382
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:387
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
			yyVAL.node.(*BinaryExpr).VectorMatching.On = true
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:397
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardManyToOne
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:403
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardOneToMany
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:412
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:414
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:416
		{
			yyVAL.strings = []string{}
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:418
		{
			yylex.(*parser).unexpected("grouping opts", "\"(\"")
			yyVAL.strings = nil
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:424
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[3].item.Val)
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:426
		{
			yyVAL.strings = []string{yyDollar[1].item.Val}
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:428
		{
			yylex.(*parser).unexpected("grouping opts", "\",\" or \")\"")
			yyVAL.strings = yyDollar[1].strings
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:432
		{
			if !isLabel(yyDollar[1].item.Val) {
				yylex.(*parser).unexpected("grouping opts", "label")
			}
			yyVAL.item = yyDollar[1].item
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:439
		{
			yylex.(*parser).unexpected("grouping opts", "label")
			yyVAL.item = Item{}
		}
	case 74:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:447
		{
			fn, exist := getFunction(yyDollar[1].item.Val)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: PositionRange{
					Start: yyDollar[1].item.Pos,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:464
		{
			yyVAL.node = yyDollar[2].node
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:466
		{
			yyVAL.node = Expressions{}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:470
		{
			yyVAL.node = append(yyDollar[1].node.(Expressions), yyDollar[3].node.(Expr))
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:472
		{
			yyVAL.node = Expressions{yyDollar[1].node.(Expr)}
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:474
		{
			yylex.(*parser).addParseErrf(yyDollar[2].item.PositionRange(), "trailing commas not allowed in function call args")
			yyVAL.node = yyDollar[1].node
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:485
		{
			yyVAL.node = &ParenExpr{Expr: yyDollar[2].node.(Expr), PosRange: mergeRanges(&yyDollar[1].item, &yyDollar[3].item)}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:493
		{
			yylex.(*parser).addOffset(yyDollar[1].node, yyDollar[3].duration)
			yyVAL.node = yyDollar[1].node
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:498
		{
			yylex.(*parser).unexpected("offset", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 83:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:506
		{
			var errMsg string
			vs, ok := yyDollar[1].node.(*VectorSelector)
			if !ok {
				errMsg = "ranges only allowed for vector selectors"
			} else if vs.Offset != 0 {
				errMsg = "no offset modifiers allowed before range"
			}

			if errMsg != "" {
				errRange := mergeRanges(&yyDollar[2].item, &yyDollar[4].item)
				yylex.(*parser).addParseErrf(errRange, errMsg)
			}

			yyVAL.node = &MatrixSelector{
				VectorSelector: yyDollar[1].node.(Expr),
				Range:          yyDollar[3].duration,
				EndPos:         yylex.(*parser).lastClosing,
			}
		}
	case 84:
		yyDollar = yyS[yypt-6 : yypt+1]
//line generated_parser.y:529
		{
			yyVAL.node = &SubqueryExpr{
				Expr:  yyDollar[1].node.(Expr),
				Range: yyDollar[3].duration,
				Step:  yyDollar[5].duration,

				EndPos: yyDollar[6].item.Pos + 1,
			}
		}
	case 85:
		yyDollar = yyS[yypt-6 : yypt+1]
//line generated_parser.y:539
		{
			yylex.(*parser).unexpected("subquery selector", "\"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 86:
		yyDollar = yyS[yypt-5 : yypt+1]
//line generated_parser.y:541
		{
			yylex.(*parser).unexpected("subquery selector", "duration or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 87:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:543
		{
			yylex.(*parser).unexpected("subquery or range", "\":\" or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:545
		{
			yylex.(*parser).unexpected("subquery selector", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:555
		{
			if nl, ok := yyDollar[2].node.(*NumberLiteral); ok {
				if yyDollar[1].item.Typ == SUB {
					nl.Val *= -1
				}
				nl.PosRange.Start = yyDollar[1].item.Pos
				yyVAL.node = nl
			} else {
				yyVAL.node = &UnaryExpr{Op: yyDollar[1].item.Typ, Expr: yyDollar[2].node.(Expr), StartPos: yyDollar[1].item.Pos}
			}
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:573
		{
			vs := yyDollar[2].node.(*VectorSelector)
			vs.PosRange = mergeRanges(&yyDollar[1].item, vs)
			vs.Name = yyDollar[1].item.Val
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:581
		{
			vs := &VectorSelector{
				Name:          yyDollar[1].item.Val,
				LabelMatchers: []*labels.Matcher{},
				PosRange:      yyDollar[1].item.PositionRange(),
			}
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:591
		{
			vs := yyDollar[1].node.(*VectorSelector)
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:599
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[3].item),
			}
		}
	case 94:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:606
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[4].item),
			}
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:613
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: []*labels.Matcher{},
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[2].item),
			}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:622
		{
			if yyDollar[1].matchers != nil {
				yyVAL.matchers = append(yyDollar[1].matchers, yyDollar[3].matcher)
			} else {
				yyVAL.matchers = yyDollar[1].matchers
			}
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:630
		{
			yyVAL.matchers = []*labels.Matcher{yyDollar[1].matcher}
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:632
		{
			yylex.(*parser).unexpected("label matching", "\",\" or \"}\"")
			yyVAL.matchers = yyDollar[1].matchers
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:636
		{
			yyVAL.matcher = yylex.(*parser).newLabelMatcher(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item)
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:638
		{
			yylex.(*parser).unexpected("label matching", "string")
			yyVAL.matcher = nil
		}
	case 101:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:640
		{
			yylex.(*parser).unexpected("label matching", "label matching operator")
			yyVAL.matcher = nil
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:642
		{
			yylex.(*parser).unexpected("label matching", "identifier or \"}\"")
			yyVAL.matcher = nil
		}
	case 103:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:650
		{
			yyVAL.labels = append(yyDollar[2].labels, labels.Label{Name: labels.MetricName, Value: yyDollar[1].item.Val})
			sort.Sort(yyVAL.labels)
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:652
		{
			yyVAL.labels = yyDollar[1].labels
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:659
		{
			yyVAL.labels = labels.New(yyDollar[2].labels...)
		}
	case 124:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:661
		{
			yyVAL.labels = labels.New(yyDollar[2].labels...)
		}
	case 125:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:663
		{
			yyVAL.labels = labels.New()
		}
	case 126:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:665
		{
			yyVAL.labels = labels.New()
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:669
		{
			yyVAL.labels = append(yyDollar[1].labels, yyDollar[3].label)
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:671
		{
			yyVAL.labels = []labels.Label{yyDollar[1].label}
		}
	case 129:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:673
		{
			yylex.(*parser).unexpected("label set", "\",\" or \"}\"")
			yyVAL.labels = yyDollar[1].labels
		}
	case 130:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:678
		{
			yyVAL.label = labels.Label{Name: yyDollar[1].item.Val, Value: yylex.(*parser).unquoteString(yyDollar[3].item.Val)}
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:680
		{
			yylex.(*parser).unexpected("label set", "string")
			yyVAL.label = labels.Label{}
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:682
		{
			yylex.(*parser).unexpected("label set", "\"=\"")
			yyVAL.label = labels.Label{}
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:684
		{
			yylex.(*parser).unexpected("label set", "identifier or \"}\"")
			yyVAL.label = labels.Label{}
		}
	case 134:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:692
		{
			yylex.(*parser).generatedParserResult = &seriesDescription{
				labels: yyDollar[1].labels,
				values: yyDollar[2].series,
			}
		}
	case 135:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:701
		{
			yyVAL.series = []SequenceValue{}
		}
	case 136:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:703
		{
			yyVAL.series = append(yyDollar[1].series, yyDollar[3].series...)
		}
	case 137:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:705
		{
			yyVAL.series = yyDollar[1].series
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:707
		{
			yylex.(*parser).unexpected("series values", "")
			yyVAL.series = nil
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:711
		{
			yyVAL.series = []SequenceValue{{Omitted: true}}
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:713
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i < yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Omitted: true})
			}
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:720
		{
			yyVAL.series = []SequenceValue{{Value: yyDollar[1].float}}
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:722
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
			}
		}
	case 143:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:729
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[4].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
				yyDollar[1].float += yyDollar[2].float
			}
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:739
		{
			fmt.Println("auxillary")
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:741
		{
			if yyDollar[1].item.Val != "stale" {
				yylex.(*parser).unexpected("series values", "number or \"stale\"")
			}
			yyVAL.float = math.Float64frombits(value.StaleNaN)
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:772
		{
			yyVAL.node = &NumberLiteral{
				Val:      yylex.(*parser).number(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:780
		{
			yyVAL.float = yylex.(*parser).number(yyDollar[1].item.Val)
		}
	case 190:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:782
		{
			yyVAL.float = yyDollar[2].float
		}
	case 191:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:783
		{
			yyVAL.float = -yyDollar[2].float
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:787
		{
			var err error
			yyVAL.uint, err = strconv.ParseUint(yyDollar[1].item.Val, 10, 64)
			if err != nil {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "invalid repetition in series values: %s", err)
			}
		}
	case 193:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:797
		{
			var err error
			yyVAL.duration, err = parseDuration(yyDollar[1].item.Val)
			if err != nil {
				yylex.(*parser).addParseErr(yyDollar[1].item.PositionRange(), err)
			}
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:808
		{
			yyVAL.node = &StringLiteral{
				Val:      yylex.(*parser).unquoteString(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 195:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:821
		{
			yyVAL.duration = 0
		}
	case 197:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:825
		{
			yyVAL.strings = nil
		}
	}
	goto yystack /* stack new state and value */
}
