// Code generated by goyacc -o generated_parser.y.go generated_parser.y. DO NOT EDIT.

//line generated_parser.y:15
package parser

import __yyfmt__ "fmt"

//line generated_parser.y:15

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"time"

	"github.com/prometheus/prometheus/pkg/labels"
	"github.com/prometheus/prometheus/pkg/value"
)

//line generated_parser.y:29
type yySymType struct {
	yys      int
	node     Node
	item     Item
	matchers []*labels.Matcher
	matcher  *labels.Matcher
	label    labels.Label
	labels   labels.Labels
	strings  []string
	series   []SequenceValue
	uint     uint64
	float    float64
	duration time.Duration
}

const ASSIGN = 57346
const BLANK = 57347
const COLON = 57348
const COMMA = 57349
const COMMENT = 57350
const DURATION = 57351
const EOF = 57352
const ERROR = 57353
const IDENTIFIER = 57354
const LEFT_BRACE = 57355
const LEFT_BRACKET = 57356
const LEFT_PAREN = 57357
const METRIC_IDENTIFIER = 57358
const NUMBER = 57359
const RIGHT_BRACE = 57360
const RIGHT_BRACKET = 57361
const RIGHT_PAREN = 57362
const SEMICOLON = 57363
const SPACE = 57364
const STRING = 57365
const TIMES = 57366
const operatorsStart = 57367
const ADD = 57368
const DIV = 57369
const EQL = 57370
const EQL_REGEX = 57371
const GTE = 57372
const GTR = 57373
const LAND = 57374
const LOR = 57375
const LSS = 57376
const LTE = 57377
const LUNLESS = 57378
const MOD = 57379
const MUL = 57380
const NEQ = 57381
const NEQ_REGEX = 57382
const POW = 57383
const SUB = 57384
const operatorsEnd = 57385
const aggregatorsStart = 57386
const AVG = 57387
const BOTTOMK = 57388
const COUNT = 57389
const COUNT_VALUES = 57390
const MAX = 57391
const MIN = 57392
const QUANTILE = 57393
const STDDEV = 57394
const STDVAR = 57395
const SUM = 57396
const TOPK = 57397
const aggregatorsEnd = 57398
const keywordsStart = 57399
const BOOL = 57400
const BY = 57401
const GROUP_LEFT = 57402
const GROUP_RIGHT = 57403
const IGNORING = 57404
const OFFSET = 57405
const ON = 57406
const WITHOUT = 57407
const keywordsEnd = 57408
const startSymbolsStart = 57409
const START_METRIC = 57410
const START_SERIES_DESCRIPTION = 57411
const START_EXPRESSION = 57412
const START_METRIC_SELECTOR = 57413
const startSymbolsEnd = 57414

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ASSIGN",
	"BLANK",
	"COLON",
	"COMMA",
	"COMMENT",
	"DURATION",
	"EOF",
	"ERROR",
	"IDENTIFIER",
	"LEFT_BRACE",
	"LEFT_BRACKET",
	"LEFT_PAREN",
	"METRIC_IDENTIFIER",
	"NUMBER",
	"RIGHT_BRACE",
	"RIGHT_BRACKET",
	"RIGHT_PAREN",
	"SEMICOLON",
	"SPACE",
	"STRING",
	"TIMES",
	"operatorsStart",
	"ADD",
	"DIV",
	"EQL",
	"EQL_REGEX",
	"GTE",
	"GTR",
	"LAND",
	"LOR",
	"LSS",
	"LTE",
	"LUNLESS",
	"MOD",
	"MUL",
	"NEQ",
	"NEQ_REGEX",
	"POW",
	"SUB",
	"operatorsEnd",
	"aggregatorsStart",
	"AVG",
	"BOTTOMK",
	"COUNT",
	"COUNT_VALUES",
	"MAX",
	"MIN",
	"QUANTILE",
	"STDDEV",
	"STDVAR",
	"SUM",
	"TOPK",
	"aggregatorsEnd",
	"keywordsStart",
	"BOOL",
	"BY",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"IGNORING",
	"OFFSET",
	"ON",
	"WITHOUT",
	"keywordsEnd",
	"startSymbolsStart",
	"START_METRIC",
	"START_SERIES_DESCRIPTION",
	"START_EXPRESSION",
	"START_METRIC_SELECTOR",
	"startSymbolsEnd",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line generated_parser.y:800

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 31,
	1, 122,
	10, 122,
	22, 122,
	-2, 0,
	-1, 54,
	2, 134,
	15, 134,
	59, 134,
	65, 134,
	-2, 92,
	-1, 55,
	2, 135,
	15, 135,
	59, 135,
	65, 135,
	-2, 93,
	-1, 56,
	2, 136,
	15, 136,
	59, 136,
	65, 136,
	-2, 95,
	-1, 57,
	2, 137,
	15, 137,
	59, 137,
	65, 137,
	-2, 96,
	-1, 58,
	2, 138,
	15, 138,
	59, 138,
	65, 138,
	-2, 101,
	-1, 59,
	2, 139,
	15, 139,
	59, 139,
	65, 139,
	-2, 103,
	-1, 60,
	2, 140,
	15, 140,
	59, 140,
	65, 140,
	-2, 105,
	-1, 61,
	2, 141,
	15, 141,
	59, 141,
	65, 141,
	-2, 106,
	-1, 62,
	2, 142,
	15, 142,
	59, 142,
	65, 142,
	-2, 107,
	-1, 63,
	2, 143,
	15, 143,
	59, 143,
	65, 143,
	-2, 108,
	-1, 64,
	2, 144,
	15, 144,
	59, 144,
	65, 144,
	-2, 109,
	-1, 176,
	12, 183,
	13, 183,
	16, 183,
	17, 183,
	23, 183,
	26, 183,
	32, 183,
	33, 183,
	36, 183,
	42, 183,
	45, 183,
	46, 183,
	47, 183,
	48, 183,
	49, 183,
	50, 183,
	51, 183,
	52, 183,
	53, 183,
	54, 183,
	55, 183,
	59, 183,
	63, 183,
	-2, 0,
	-1, 177,
	12, 183,
	13, 183,
	16, 183,
	17, 183,
	23, 183,
	26, 183,
	32, 183,
	33, 183,
	36, 183,
	42, 183,
	45, 183,
	46, 183,
	47, 183,
	48, 183,
	49, 183,
	50, 183,
	51, 183,
	52, 183,
	53, 183,
	54, 183,
	55, 183,
	59, 183,
	63, 183,
	-2, 0,
	-1, 193,
	19, 181,
	-2, 0,
	-1, 240,
	19, 182,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 555

var yyAct = [...]int{

	246, 34, 197, 136, 237, 236, 169, 108, 72, 168,
	99, 97, 96, 176, 177, 6, 100, 174, 199, 175,
	121, 115, 230, 94, 171, 249, 229, 116, 208, 250,
	98, 224, 214, 228, 77, 53, 252, 244, 247, 163,
	172, 153, 243, 101, 223, 101, 152, 114, 210, 211,
	91, 103, 212, 104, 227, 242, 67, 151, 117, 102,
	162, 200, 202, 204, 205, 213, 215, 218, 219, 220,
	221, 222, 93, 94, 201, 203, 206, 207, 209, 216,
	217, 2, 3, 4, 5, 78, 79, 99, 105, 170,
	194, 29, 7, 100, 193, 95, 88, 89, 139, 110,
	91, 92, 74, 149, 143, 146, 241, 192, 141, 109,
	142, 45, 73, 138, 251, 225, 140, 68, 160, 173,
	76, 161, 93, 138, 178, 179, 180, 181, 182, 183,
	184, 185, 186, 187, 188, 189, 190, 191, 122, 123,
	124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
	134, 135, 30, 110, 1, 165, 199, 239, 155, 113,
	226, 74, 167, 109, 112, 145, 208, 170, 8, 107,
	214, 73, 31, 231, 196, 111, 171, 71, 144, 234,
	235, 232, 233, 238, 156, 158, 210, 211, 44, 43,
	212, 137, 172, 42, 41, 157, 159, 240, 138, 200,
	202, 204, 205, 213, 215, 218, 219, 220, 221, 222,
	120, 10, 201, 203, 206, 207, 209, 216, 217, 40,
	32, 69, 33, 39, 47, 67, 245, 49, 21, 48,
	52, 248, 38, 9, 9, 50, 118, 147, 65, 37,
	119, 36, 35, 166, 17, 18, 253, 75, 19, 164,
	254, 195, 70, 51, 66, 198, 154, 54, 55, 56,
	57, 58, 59, 60, 61, 62, 63, 64, 46, 47,
	67, 13, 49, 21, 48, 23, 106, 148, 0, 0,
	50, 0, 0, 65, 0, 0, 0, 0, 0, 17,
	18, 0, 0, 19, 0, 0, 0, 0, 0, 66,
	0, 0, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 0, 47, 67, 13, 49, 21, 48,
	23, 0, 0, 0, 0, 50, 0, 0, 65, 0,
	0, 0, 0, 0, 17, 18, 0, 0, 19, 16,
	67, 0, 0, 21, 66, 0, 0, 54, 55, 56,
	57, 58, 59, 60, 61, 62, 63, 64, 0, 17,
	18, 13, 0, 19, 0, 23, 0, 16, 29, 0,
	94, 21, 11, 12, 14, 15, 20, 22, 24, 25,
	26, 27, 28, 79, 0, 0, 13, 17, 18, 0,
	23, 19, 0, 88, 89, 0, 0, 91, 0, 0,
	11, 12, 14, 15, 20, 22, 24, 25, 26, 27,
	28, 94, 0, 0, 13, 0, 0, 150, 23, 93,
	0, 0, 0, 78, 79, 80, 0, 81, 82, 83,
	84, 85, 86, 87, 88, 89, 90, 0, 91, 92,
	0, 0, 0, 0, 0, 94, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 78, 79, 80,
	93, 81, 82, 83, 84, 85, 86, 87, 88, 89,
	90, 0, 91, 92, 0, 94, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 78, 79, 80,
	0, 81, 82, 83, 93, 85, 86, 87, 88, 89,
	90, 0, 91, 92, 0, 94, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 78, 79, 80,
	0, 81, 82, 0, 93, 85, 86, 0, 88, 89,
	90, 0, 91, 92, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 93,
}
var yyPact = [...]int{

	13, 82, 355, 355, 212, 327, -1000, -1000, -1000, 78,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 159,
	-1000, 118, 302, -1000, 431, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 87, 28, 30, -1000, 302,
	-1000, 302, 43, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 151, -1000, -1000,
	157, -1000, -1000, 19, -1000, 5, -1000, 431, -38, -38,
	-38, -38, -38, -38, -38, -38, -38, -38, -38, -38,
	-38, -38, -38, 189, 114, -1000, 30, -49, -1000, 163,
	163, 257, -1000, 397, 9, -1000, 39, -1000, -1000, 156,
	-1000, -1000, 100, -1000, 37, -1000, 150, 302, -1000, -45,
	-47, -1000, 302, 302, 302, 302, 302, 302, 302, 302,
	302, 302, 302, 302, 302, 302, -1000, -1000, -1000, 88,
	-1000, -1000, -1000, -1000, 154, -1000, -1000, 24, -1000, 431,
	-1000, -1000, 97, -1000, 31, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 2, -2, -1000, -1000, -1000,
	-1000, 72, 72, 356, 163, 163, 163, 163, 9, 59,
	59, 59, 491, 461, 59, 59, 491, 9, 9, 59,
	9, 356, -1000, 104, -1000, 35, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 302, -1000, -1000, -1000, -1000, 21,
	21, 1, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 10,
	112, -1000, -1000, 16, -1000, 431, -1000, -1000, -1000, 21,
	-1000, -1000, -1000, -1000, -1000,
}
var yyPgo = [...]int{

	0, 276, 7, 268, 2, 256, 255, 230, 253, 211,
	252, 168, 8, 251, 4, 5, 249, 247, 0, 9,
	243, 6, 242, 12, 58, 241, 240, 1, 239, 237,
	11, 236, 35, 232, 223, 219, 210, 194, 193, 189,
	188, 111, 3, 157, 154, 152,
}
var yyR1 = [...]int{

	0, 44, 44, 44, 44, 44, 44, 44, 44, 44,
	27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
	27, 27, 22, 22, 22, 22, 23, 23, 25, 25,
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 24, 26, 26, 36, 36, 31, 31,
	31, 31, 14, 14, 14, 14, 13, 13, 13, 4,
	4, 28, 30, 30, 29, 29, 29, 37, 35, 35,
	33, 39, 39, 39, 39, 39, 40, 41, 41, 41,
	32, 32, 32, 1, 1, 1, 2, 2, 2, 2,
	11, 11, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	9, 9, 9, 9, 10, 10, 10, 12, 12, 12,
	12, 45, 17, 17, 17, 17, 16, 16, 16, 16,
	16, 20, 20, 20, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 8, 8,
	5, 5, 5, 5, 34, 19, 21, 21, 18, 42,
	38, 43, 43, 15, 15,
}
var yyR2 = [...]int{

	0, 2, 2, 2, 3, 2, 2, 2, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 3, 3, 2, 2, 2, 2, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 1, 0, 1, 3, 3, 1, 1,
	3, 3, 3, 4, 2, 1, 3, 1, 2, 1,
	1, 2, 3, 2, 3, 1, 2, 3, 3, 3,
	4, 6, 6, 5, 4, 3, 2, 2, 1, 1,
	3, 4, 2, 3, 1, 2, 3, 3, 2, 1,
	2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 4, 2, 0, 3, 1, 2, 3, 3, 2,
	1, 2, 0, 3, 2, 1, 1, 3, 1, 3,
	4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 2, 1, 1,
	1, 0, 1, 0, 1,
}
var yyChk = [...]int{

	-1000, -44, 68, 69, 70, 71, 2, 10, -11, -7,
	-9, 45, 46, 59, 47, 48, 12, 32, 33, 36,
	49, 16, 50, 63, 51, 52, 53, 54, 55, 13,
	-45, -11, 8, 10, -27, -22, -25, -28, -33, -34,
	-35, -37, -38, -39, -40, -41, -3, 12, 17, 15,
	23, -8, -7, -32, 45, 46, 47, 48, 49, 50,
	51, 52, 53, 54, 55, 26, 42, 13, -41, -9,
	-10, 18, -12, 12, 2, -17, 2, -27, 26, 27,
	28, 30, 31, 32, 33, 34, 35, 36, 37, 38,
	39, 41, 42, 63, 14, 8, -23, -30, 2, 59,
	65, 15, -30, -27, -27, -32, -1, 18, -2, 12,
	2, 18, 7, 2, 28, 2, 22, -24, -31, -26,
	-36, 58, -24, -24, -24, -24, -24, -24, -24, -24,
	-24, -24, -24, -24, -24, -24, -42, 2, 9, -42,
	2, -30, -23, -14, 15, 2, -14, -29, 20, -27,
	20, 18, 7, 2, -5, 2, 28, 39, 29, 40,
	18, -12, 23, 2, -16, 5, -20, 12, -19, -21,
	17, 26, 42, -27, 62, 64, 60, 61, -27, -27,
	-27, -27, -27, -27, -27, -27, -27, -27, -27, -27,
	-27, -27, 19, 6, 2, -13, 20, -4, -6, 2,
	45, 58, 46, 59, 47, 48, 60, 61, 12, 62,
	32, 33, 36, 49, 16, 50, 63, 64, 51, 52,
	53, 54, 55, 20, 7, 18, -2, 23, 2, 24,
	24, -21, -19, -19, -14, -14, -15, -14, -15, -43,
	-42, 2, 20, 7, 2, -27, -18, 17, -18, 24,
	19, 2, 20, -4, -18,
}
var yyDef = [...]int{

	0, -2, 113, 113, 0, 0, 9, 8, 1, 113,
	91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
	101, 102, 103, 104, 105, 106, 107, 108, 109, 0,
	2, -2, 3, 5, 6, 10, 11, 12, 13, 14,
	15, 16, 17, 18, 19, 20, 0, 97, 174, 0,
	180, 0, 78, 79, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, 168, 169, 0, 7, 90,
	0, 112, 115, 0, 120, 121, 125, 4, 44, 44,
	44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
	44, 44, 44, 0, 0, 21, 0, 24, 25, 0,
	0, 0, 61, 0, 76, 77, 0, 82, 84, 0,
	89, 110, 0, 116, 0, 119, 124, 0, 43, 48,
	49, 45, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 68, 69, 179, 0,
	75, 22, 23, 26, 0, 55, 27, 0, 63, 65,
	67, 80, 0, 85, 0, 88, 170, 171, 172, 173,
	111, 114, 117, 118, 123, 126, 128, 131, 132, 133,
	175, 0, 0, 28, 0, 0, -2, -2, 29, 30,
	31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
	41, 42, 70, -2, 74, 0, 54, 57, 59, 60,
	145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
	155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
	165, 166, 167, 62, 66, 81, 83, 86, 87, 0,
	0, 0, 176, 177, 46, 47, 50, 184, 51, 0,
	-2, 73, 52, 0, 58, 64, 127, 178, 129, 0,
	71, 72, 53, 56, 130,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:165
		{

			fmt.Println("going through")
			yylex.(*parser).generatedParserResult = yyDollar[2].labels
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:172
		{
			fmt.Println("inside the ONLY")
			fmt.Println("positiononle is ")
			fmt.Println(yyDollar[2].item.PositionRange())
			fmt.Println(yyDollar[2].item.Val)
			ce := &CommentExpr{
				Comment:  yyDollar[2].item.Val,
				PosRange: yyDollar[2].item.PositionRange(),
			}
			// yylex.(*parser).comments = append(yylex.(*parser).comments, ce)

			yylex.(*parser).generatedParserResult = ce
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:186
		{
			fmt.Println("third case ")
			fmt.Println("comment -> ", yyDollar[2].item)
			fmt.Println("expr -> ", yyDollar[3].node)
			ce := &CommentExpr{
				Comment:  yyDollar[2].item.Val,
				Expr:     yyDollar[3].node.(Expr),
				PosRange: yyDollar[3].node.PositionRange(),
			}
			yylex.(*parser).generatedParserResult = ce

		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:199
		{
			yylex.(*parser).addParseErrf(PositionRange{}, "no expression found in input")
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:212
		{
			fmt.Println("normal expr")
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:216
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:219
		{
			yylex.(*parser).unexpected("", "")
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:248
		{
			fmt.Println("this being here ", yyDollar[2].item)
			ce := &CommentExpr{
				Comment:  yyDollar[2].item.Val,
				Expr:     yyDollar[1].node.(Expr),
				PosRange: yyDollar[2].item.PositionRange(),
			}
			fmt.Println("ce is ", ce)
			fmt.Println("and its expr is ", ce.Expr)
			yyVAL.node = ce
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:266
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[2].node, yyDollar[3].node)
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:268
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[3].node, yyDollar[2].node)
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:270
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, yyDollar[2].node)
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:272
		{
			yylex.(*parser).unexpected("aggregation", "")
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, Expressions{})
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:280
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
			}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:286
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
				Without:  true,
			}
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:299
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:300
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:301
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:302
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:303
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:304
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:305
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:306
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:307
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:308
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:309
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:310
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:311
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:312
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:313
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 44:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:321
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
			}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:326
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
				ReturnBool:     true,
			}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:334
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:339
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
			yyVAL.node.(*BinaryExpr).VectorMatching.On = true
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:349
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardManyToOne
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:355
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardOneToMany
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:364
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:366
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:368
		{
			yyVAL.strings = []string{}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:370
		{
			yylex.(*parser).unexpected("grouping opts", "\"(\"")
			yyVAL.strings = nil
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:376
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[3].item.Val)
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:378
		{
			yyVAL.strings = []string{yyDollar[1].item.Val}
		}
	case 58:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:380
		{
			yylex.(*parser).unexpected("grouping opts", "\",\" or \")\"")
			yyVAL.strings = yyDollar[1].strings
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:384
		{
			if !isLabel(yyDollar[1].item.Val) {
				yylex.(*parser).unexpected("grouping opts", "label")
			}
			yyVAL.item = yyDollar[1].item
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:391
		{
			yylex.(*parser).unexpected("grouping opts", "label")
			yyVAL.item = Item{}
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:399
		{
			fn, exist := getFunction(yyDollar[1].item.Val)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: PositionRange{
					Start: yyDollar[1].item.Pos,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:416
		{
			yyVAL.node = yyDollar[2].node
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:418
		{
			yyVAL.node = Expressions{}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:422
		{
			yyVAL.node = append(yyDollar[1].node.(Expressions), yyDollar[3].node.(Expr))
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:424
		{
			yyVAL.node = Expressions{yyDollar[1].node.(Expr)}
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:426
		{
			yylex.(*parser).addParseErrf(yyDollar[2].item.PositionRange(), "trailing commas not allowed in function call args")
			yyVAL.node = yyDollar[1].node
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:437
		{
			yyVAL.node = &ParenExpr{Expr: yyDollar[2].node.(Expr), PosRange: mergeRanges(&yyDollar[1].item, &yyDollar[3].item)}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:445
		{
			yylex.(*parser).addOffset(yyDollar[1].node, yyDollar[3].duration)
			yyVAL.node = yyDollar[1].node
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:450
		{
			yylex.(*parser).unexpected("offset", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:458
		{
			var errMsg string
			vs, ok := yyDollar[1].node.(*VectorSelector)
			if !ok {
				errMsg = "ranges only allowed for vector selectors"
			} else if vs.Offset != 0 {
				errMsg = "no offset modifiers allowed before range"
			}

			if errMsg != "" {
				errRange := mergeRanges(&yyDollar[2].item, &yyDollar[4].item)
				yylex.(*parser).addParseErrf(errRange, errMsg)
			}

			yyVAL.node = &MatrixSelector{
				VectorSelector: yyDollar[1].node.(Expr),
				Range:          yyDollar[3].duration,
				EndPos:         yylex.(*parser).lastClosing,
			}
		}
	case 71:
		yyDollar = yyS[yypt-6 : yypt+1]
//line generated_parser.y:481
		{
			yyVAL.node = &SubqueryExpr{
				Expr:  yyDollar[1].node.(Expr),
				Range: yyDollar[3].duration,
				Step:  yyDollar[5].duration,

				EndPos: yyDollar[6].item.Pos + 1,
			}
		}
	case 72:
		yyDollar = yyS[yypt-6 : yypt+1]
//line generated_parser.y:491
		{
			yylex.(*parser).unexpected("subquery selector", "\"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 73:
		yyDollar = yyS[yypt-5 : yypt+1]
//line generated_parser.y:493
		{
			yylex.(*parser).unexpected("subquery selector", "duration or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 74:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:495
		{
			yylex.(*parser).unexpected("subquery or range", "\":\" or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:497
		{
			yylex.(*parser).unexpected("subquery selector", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:507
		{
			if nl, ok := yyDollar[2].node.(*NumberLiteral); ok {
				if yyDollar[1].item.Typ == SUB {
					nl.Val *= -1
				}
				nl.PosRange.Start = yyDollar[1].item.Pos
				yyVAL.node = nl
			} else {
				yyVAL.node = &UnaryExpr{Op: yyDollar[1].item.Typ, Expr: yyDollar[2].node.(Expr), StartPos: yyDollar[1].item.Pos}
			}
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:525
		{
			fmt.Println("vector selector 1")
			vs := yyDollar[2].node.(*VectorSelector)
			vs.PosRange = mergeRanges(&yyDollar[1].item, vs)
			vs.Name = yyDollar[1].item.Val
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:534
		{
			fmt.Println("vector selector 2")
			vs := &VectorSelector{
				Name:          yyDollar[1].item.Val,
				LabelMatchers: []*labels.Matcher{},
				PosRange:      yyDollar[1].item.PositionRange(),
			}
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:564
		{
			vs := yyDollar[1].node.(*VectorSelector)
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:572
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[3].item),
			}
		}
	case 81:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:579
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[4].item),
			}
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:586
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: []*labels.Matcher{},
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[2].item),
			}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:595
		{
			if yyDollar[1].matchers != nil {
				yyVAL.matchers = append(yyDollar[1].matchers, yyDollar[3].matcher)
			} else {
				yyVAL.matchers = yyDollar[1].matchers
			}
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:603
		{
			yyVAL.matchers = []*labels.Matcher{yyDollar[1].matcher}
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:605
		{
			yylex.(*parser).unexpected("label matching", "\",\" or \"}\"")
			yyVAL.matchers = yyDollar[1].matchers
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:609
		{
			yyVAL.matcher = yylex.(*parser).newLabelMatcher(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item)
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:611
		{
			yylex.(*parser).unexpected("label matching", "string")
			yyVAL.matcher = nil
		}
	case 88:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:613
		{
			yylex.(*parser).unexpected("label matching", "label matching operator")
			yyVAL.matcher = nil
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:615
		{
			yylex.(*parser).unexpected("label matching", "identifier or \"}\"")
			yyVAL.matcher = nil
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:623
		{
			yyVAL.labels = append(yyDollar[2].labels, labels.Label{Name: labels.MetricName, Value: yyDollar[1].item.Val})
			sort.Sort(yyVAL.labels)
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:625
		{
			yyVAL.labels = yyDollar[1].labels
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:632
		{
			yyVAL.labels = labels.New(yyDollar[2].labels...)
		}
	case 111:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:634
		{
			yyVAL.labels = labels.New(yyDollar[2].labels...)
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:636
		{
			yyVAL.labels = labels.New()
		}
	case 113:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:638
		{
			yyVAL.labels = labels.New()
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:642
		{
			yyVAL.labels = append(yyDollar[1].labels, yyDollar[3].label)
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:644
		{
			yyVAL.labels = []labels.Label{yyDollar[1].label}
		}
	case 116:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:646
		{
			yylex.(*parser).unexpected("label set", "\",\" or \"}\"")
			yyVAL.labels = yyDollar[1].labels
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:651
		{
			yyVAL.label = labels.Label{Name: yyDollar[1].item.Val, Value: yylex.(*parser).unquoteString(yyDollar[3].item.Val)}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:653
		{
			yylex.(*parser).unexpected("label set", "string")
			yyVAL.label = labels.Label{}
		}
	case 119:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:655
		{
			yylex.(*parser).unexpected("label set", "\"=\"")
			yyVAL.label = labels.Label{}
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:657
		{
			yylex.(*parser).unexpected("label set", "identifier or \"}\"")
			yyVAL.label = labels.Label{}
		}
	case 121:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:665
		{
			yylex.(*parser).generatedParserResult = &seriesDescription{
				labels: yyDollar[1].labels,
				values: yyDollar[2].series,
			}
		}
	case 122:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:674
		{
			yyVAL.series = []SequenceValue{}
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:676
		{
			yyVAL.series = append(yyDollar[1].series, yyDollar[3].series...)
		}
	case 124:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:678
		{
			yyVAL.series = yyDollar[1].series
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:680
		{
			yylex.(*parser).unexpected("series values", "")
			yyVAL.series = nil
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:684
		{
			yyVAL.series = []SequenceValue{{Omitted: true}}
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:686
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i < yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Omitted: true})
			}
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:693
		{
			yyVAL.series = []SequenceValue{{Value: yyDollar[1].float}}
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:695
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
			}
		}
	case 130:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:702
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[4].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
				yyDollar[1].float += yyDollar[2].float
			}
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:712
		{
			if yyDollar[1].item.Val != "stale" {
				yylex.(*parser).unexpected("series values", "number or \"stale\"")
			}
			yyVAL.float = math.Float64frombits(value.StaleNaN)
		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:743
		{
			yyVAL.node = &NumberLiteral{
				Val:      yylex.(*parser).number(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:751
		{
			yyVAL.float = yylex.(*parser).number(yyDollar[1].item.Val)
		}
	case 176:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:753
		{
			yyVAL.float = yyDollar[2].float
		}
	case 177:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:754
		{
			yyVAL.float = -yyDollar[2].float
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:758
		{
			var err error
			yyVAL.uint, err = strconv.ParseUint(yyDollar[1].item.Val, 10, 64)
			if err != nil {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "invalid repetition in series values: %s", err)
			}
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:768
		{
			var err error
			yyVAL.duration, err = parseDuration(yyDollar[1].item.Val)
			if err != nil {
				yylex.(*parser).addParseErr(yyDollar[1].item.PositionRange(), err)
			}
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:779
		{
			yyVAL.node = &StringLiteral{
				Val:      yylex.(*parser).unquoteString(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 181:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:792
		{
			yyVAL.duration = 0
		}
	case 183:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:796
		{
			yyVAL.strings = nil
		}
	}
	goto yystack /* stack new state and value */
}
